import { useLanguage } from "@/contexts/LanguageContext";
import { translateGameData } from "@/i18n/gameData";
import { Button } from "@/components/ui/button";
import { Printer, Download } from "lucide-react";

interface FactionSheetProps {
  faction: {
    nom: string;
    marquesTotal: number;
    marquesDepensees: number;
    marquesDisponibles: number;
    propriete: string;
    batiment: { type: string; nom: string; avantages: string } | null;
    titres: string[];
    descriptionCourte: string;
    background: string;
    contactEmail: string;
    dateCreation: string;
  };
}

export const FactionSheet = ({ faction }: FactionSheetProps) => {
  const { t, language } = useLanguage();

  const generateSheetHTML = () => {
    const labels = {
      title: language === 'en' ? 'FACTION SHEET' : 'FICHE DE FACTION',
      factionName: language === 'en' ? 'Faction Name' : 'Nom de la Faction',
      destinyMarks: language === 'en' ? 'Destiny Marks' : 'Marques de Destinée',
      total: language === 'en' ? 'Total' : 'Total',
      spent: language === 'en' ? 'Spent' : 'Dépensées',
      available: language === 'en' ? 'Available' : 'Disponibles',
      landProperty: language === 'en' ? 'Land Property' : 'Propriété Terrienne',
      buildingShip: language === 'en' ? 'Building/Ship' : 'Bâtiment/Navire',
      building: language === 'en' ? 'Building' : 'Bâtiment',
      ship: language === 'en' ? 'Ship' : 'Navire',
      advantages: language === 'en' ? 'Advantages' : 'Avantages',
      titlesCareers: language === 'en' ? 'Titles/Careers' : 'Titres/Carrières',
      shortDescription: language === 'en' ? 'Short Description' : 'Description Courte',
      background: language === 'en' ? 'Background' : 'Background',
      contactEmail: language === 'en' ? 'Contact Email' : 'Email de Contact',
      creationDate: language === 'en' ? 'Creation Date' : 'Date de Création',
      none: language === 'en' ? 'None' : 'Aucun(e)',
      autoGenerated: language === 'en' ? 'Automatically generated sheet' : 'Fiche générée automatiquement',
      contactOrga: language === 'en' ? 'For any modification, contact the organization' : 'Pour toute modification, contactez l\'organisation',
    };

    const batimentType = faction.batiment?.type === 'Bâtiment' 
      ? labels.building 
      : faction.batiment?.type === 'Navire' 
        ? labels.ship 
        : faction.batiment?.type || '';

    return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${faction.nom}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    @page {
      size: A4 portrait;
      margin: 15mm;
    }
    
    body {
      font-family: 'Crimson Text', Georgia, serif;
      background: #f5f0e6;
      color: #2c1810;
      font-size: 11pt;
      line-height: 1.4;
    }
    
    .sheet {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      padding: 20mm;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }
    
    @media print {
      body {
        background: #fff;
      }
      .sheet {
        box-shadow: none;
        padding: 0;
      }
    }
    
    .header {
      text-align: center;
      border-bottom: 3px double #6B1836;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    
    .header h1 {
      font-family: 'Cinzel', serif;
      font-size: 24pt;
      color: #6B1836;
      margin-bottom: 5px;
      letter-spacing: 3px;
    }
    
    .header .subtitle {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #D4A851;
      letter-spacing: 2px;
    }
    
    .faction-name {
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 20pt;
      color: #2c1810;
      margin: 20px 0;
      padding: 15px;
      background: linear-gradient(90deg, transparent, rgba(107,24,54,0.1), transparent);
      border-top: 1px solid #D4A851;
      border-bottom: 1px solid #D4A851;
    }
    
    .section {
      margin-bottom: 18px;
    }
    
    .section-title {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #6B1836;
      border-bottom: 1px solid #D4A851;
      padding-bottom: 5px;
      margin-bottom: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .marks-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      text-align: center;
    }
    
    .mark-box {
      padding: 15px;
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
    }
    
    .mark-label {
      font-size: 9pt;
      color: #666;
      margin-bottom: 5px;
      text-transform: uppercase;
    }
    
    .mark-value {
      font-family: 'Cinzel', serif;
      font-size: 20pt;
      color: #6B1836;
      font-weight: 600;
    }
    
    .info-row {
      display: flex;
      margin-bottom: 8px;
    }
    
    .info-label {
      font-weight: 600;
      color: #6B1836;
      min-width: 150px;
    }
    
    .info-value {
      flex: 1;
    }
    
    .building-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 15px;
    }
    
    .building-name {
      font-family: 'Cinzel', serif;
      font-size: 13pt;
      color: #6B1836;
      margin-bottom: 5px;
    }
    
    .building-type {
      font-size: 9pt;
      color: #888;
      text-transform: uppercase;
      margin-bottom: 10px;
    }
    
    .building-advantages {
      font-style: italic;
      background: rgba(212,168,81,0.1);
      padding: 10px;
      border-radius: 3px;
      border-left: 3px solid #D4A851;
    }
    
    .titles-list {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
    }
    
    .title-badge {
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      padding: 8px 15px;
      border-radius: 20px;
      font-family: 'Cinzel', serif;
      font-size: 10pt;
    }
    
    .description-text {
      font-style: italic;
      padding: 10px;
      background: #f9f6f0;
      border-radius: 5px;
      border-left: 3px solid #D4A851;
    }
    
    .background-text {
      padding: 15px;
      background: #f9f6f0;
      border-radius: 5px;
      white-space: pre-wrap;
      line-height: 1.6;
    }
    
    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #D4A851;
      display: flex;
      justify-content: space-between;
      font-size: 9pt;
      color: #888;
    }
    
    .footer-note {
      text-align: center;
      margin-top: 20px;
      font-size: 8pt;
      color: #aaa;
    }
    
    .empty {
      color: #999;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <h1>BAROK GN</h1>
      <div class="subtitle">${labels.title}</div>
    </div>
    
    <div class="faction-name">${faction.nom}</div>
    
    <div class="section">
      <div class="section-title">${labels.destinyMarks}</div>
      <div class="marks-grid">
        <div class="mark-box">
          <div class="mark-label">${labels.total}</div>
          <div class="mark-value">${faction.marquesTotal}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.spent}</div>
          <div class="mark-value">${faction.marquesDepensees * 2}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.available}</div>
          <div class="mark-value">${faction.marquesDisponibles}</div>
        </div>
      </div>
    </div>
    
    <div class="section">
      <div class="section-title">${labels.landProperty}</div>
      ${faction.propriete 
        ? `<div class="info-value">${faction.propriete}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.buildingShip}</div>
      ${faction.batiment 
        ? `<div class="building-card">
            <div class="building-name">${translateGameData(faction.batiment.nom, 'batiment', language)}</div>
            <div class="building-type">${batimentType}</div>
            <div class="building-advantages">${labels.advantages}: ${translateGameData(faction.batiment.avantages, 'batimentAvantage', language)}</div>
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.titlesCareers}</div>
      ${faction.titres.length > 0 
        ? `<div class="titles-list">
            ${faction.titres.map(titre => 
              `<span class="title-badge">${translateGameData(titre, 'titre', language)}</span>`
            ).join('')}
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.shortDescription}</div>
      ${faction.descriptionCourte 
        ? `<div class="description-text">${faction.descriptionCourte}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.background}</div>
      ${faction.background 
        ? `<div class="background-text">${faction.background}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="footer">
      <div>${labels.contactEmail}: ${faction.contactEmail}</div>
      <div>${labels.creationDate}: ${faction.dateCreation}</div>
    </div>
    
    <div class="footer-note">
      <p>${labels.autoGenerated} - Barok GN</p>
      <p>${labels.contactOrga}</p>
    </div>
  </div>
</body>
</html>
    `;
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(generateSheetHTML());
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(generateSheetHTML());
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  return (
    <div className="flex gap-2">
      <Button onClick={handlePrint} variant="outline" className="gap-2">
        <Printer className="h-4 w-4" />
        {language === 'en' ? 'Print' : 'Imprimer'}
      </Button>
      <Button onClick={handleDownloadPDF} className="gap-2">
        <Download className="h-4 w-4" />
        {language === 'en' ? 'Download PDF' : 'Télécharger PDF'}
      </Button>
    </div>
  );
};

export const openFactionSheet = (faction: {
  nom: string;
  marquesTotal: number;
  marquesDepensees: number;
  marquesDisponibles: number;
  propriete: string;
  batiment: { type: string; nom: string; avantages: string } | null;
  titres: string[];
  descriptionCourte: string;
  background: string;
  contactEmail: string;
  dateCreation: string;
}, language: 'fr' | 'en') => {
  const labels = {
    title: language === 'en' ? 'FACTION SHEET' : 'FICHE DE FACTION',
    factionName: language === 'en' ? 'Faction Name' : 'Nom de la Faction',
    destinyMarks: language === 'en' ? 'Destiny Marks' : 'Marques de Destinée',
    total: language === 'en' ? 'Total' : 'Total',
    spent: language === 'en' ? 'Spent' : 'Dépensées',
    available: language === 'en' ? 'Available' : 'Disponibles',
    landProperty: language === 'en' ? 'Land Property' : 'Propriété Terrienne',
    buildingShip: language === 'en' ? 'Building/Ship' : 'Bâtiment/Navire',
    building: language === 'en' ? 'Building' : 'Bâtiment',
    ship: language === 'en' ? 'Ship' : 'Navire',
    advantages: language === 'en' ? 'Advantages' : 'Avantages',
    titlesCareers: language === 'en' ? 'Titles/Careers' : 'Titres/Carrières',
    shortDescription: language === 'en' ? 'Short Description' : 'Description Courte',
    background: language === 'en' ? 'Background' : 'Background',
    contactEmail: language === 'en' ? 'Contact Email' : 'Email de Contact',
    creationDate: language === 'en' ? 'Creation Date' : 'Date de Création',
    none: language === 'en' ? 'None' : 'Aucun(e)',
    autoGenerated: language === 'en' ? 'Automatically generated sheet' : 'Fiche générée automatiquement',
    contactOrga: language === 'en' ? 'For any modification, contact the organization' : 'Pour toute modification, contactez l\'organisation',
  };

  const batimentType = faction.batiment?.type === 'Bâtiment' 
    ? labels.building 
    : faction.batiment?.type === 'Navire' 
      ? labels.ship 
      : faction.batiment?.type || '';

  // Helper function for translations
  const translateBatiment = (text: string) => {
    // Import the translations directly
    const batimentTranslations: Record<string, string> = {
      "QG de Faction": "Faction HQ",
      "Entrepôt": "Warehouse",
      "Laboratoire d'Alchimie": "Alchemy Laboratory",
      "Temple/Chapelle": "Temple/Chapel",
      "Académie": "Academy",
      "Tour d'Observation": "Observation Tower",
      "Salle de Réception": "Reception Hall",
      "Prison/Cachot": "Prison/Dungeon",
      "Forge/Atelier": "Forge/Workshop",
      "Barque fluviale": "River boat",
      "Galère": "Galley",
      "Navire de guerre": "Warship",
      "Navire marchand": "Merchant ship",
      "Zeppelin": "Zeppelin",
      "Navire volant": "Airship"
    };
    return language === 'en' ? (batimentTranslations[text] || text) : text;
  };

  const translateAvantage = (text: string) => {
    const avantageTranslations: Record<string, string> = {
      "Siège, réunions secrètes": "Headquarters, secret meetings",
      "Stockage de marchandises en masse": "Mass goods storage",
      "Préparation potions et expérimentations": "Potion preparation and experimentation",
      "Centre spirituel, rituels religieux": "Spiritual center, religious rituals",
      "Formation et enseignement": "Training and education",
      "Surveillance et repérage": "Surveillance and spotting",
      "Événements sociaux et politiques": "Social and political events",
      "Détention et interrogation": "Detention and interrogation",
      "Artisanat et réparations": "Crafting and repairs",
      "Transport fluvial léger": "Light river transport",
      "Transport fluvial et combat": "River transport and combat",
      "Combat naval, transport de troupes": "Naval combat, troop transport",
      "Commerce maritime, transport de marchandises": "Maritime trade, goods transport",
      "Transport aérien, reconnaissance": "Air transport, reconnaissance",
      "Combat aérien, transport de troupes": "Air combat, troop transport"
    };
    return language === 'en' ? (avantageTranslations[text] || text) : text;
  };

  const translateTitre = (text: string) => {
    const titreTranslations: Record<string, string> = {
      "Baron-ne": "Baron/Baroness",
      "Marquis-e": "Marquis/Marchioness",
      "Comte-sse": "Count/Countess",
      "Capitaine de navire": "Ship Captain",
      "Capitaine de navire volant": "Airship Captain",
      "Ambassadeur-rice": "Ambassador",
      "Évêque": "Bishop",
      "Grand-e Inquisiteur-rice": "Grand Inquisitor",
      "Maître-sse de Guilde": "Guild Master",
      "Chef de Clan": "Clan Chief"
    };
    return language === 'en' ? (titreTranslations[text] || text) : text;
  };

  const html = `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${faction.nom}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    @page {
      size: A4 portrait;
      margin: 15mm;
    }
    
    body {
      font-family: 'Crimson Text', Georgia, serif;
      background: #f5f0e6;
      color: #2c1810;
      font-size: 11pt;
      line-height: 1.4;
    }
    
    .sheet {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      padding: 20mm;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }
    
    @media print {
      body {
        background: #fff;
      }
      .sheet {
        box-shadow: none;
        padding: 0;
      }
    }
    
    .header {
      text-align: center;
      border-bottom: 3px double #6B1836;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    
    .header h1 {
      font-family: 'Cinzel', serif;
      font-size: 24pt;
      color: #6B1836;
      margin-bottom: 5px;
      letter-spacing: 3px;
    }
    
    .header .subtitle {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #D4A851;
      letter-spacing: 2px;
    }
    
    .faction-name {
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 20pt;
      color: #2c1810;
      margin: 20px 0;
      padding: 15px;
      background: linear-gradient(90deg, transparent, rgba(107,24,54,0.1), transparent);
      border-top: 1px solid #D4A851;
      border-bottom: 1px solid #D4A851;
    }
    
    .section {
      margin-bottom: 18px;
    }
    
    .section-title {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #6B1836;
      border-bottom: 1px solid #D4A851;
      padding-bottom: 5px;
      margin-bottom: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .marks-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      text-align: center;
    }
    
    .mark-box {
      padding: 15px;
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
    }
    
    .mark-label {
      font-size: 9pt;
      color: #666;
      margin-bottom: 5px;
      text-transform: uppercase;
    }
    
    .mark-value {
      font-family: 'Cinzel', serif;
      font-size: 20pt;
      color: #6B1836;
      font-weight: 600;
    }
    
    .info-row {
      display: flex;
      margin-bottom: 8px;
    }
    
    .info-label {
      font-weight: 600;
      color: #6B1836;
      min-width: 150px;
    }
    
    .info-value {
      flex: 1;
    }
    
    .building-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 15px;
    }
    
    .building-name {
      font-family: 'Cinzel', serif;
      font-size: 13pt;
      color: #6B1836;
      margin-bottom: 5px;
    }
    
    .building-type {
      font-size: 9pt;
      color: #888;
      text-transform: uppercase;
      margin-bottom: 10px;
    }
    
    .building-advantages {
      font-style: italic;
      background: rgba(212,168,81,0.1);
      padding: 10px;
      border-radius: 3px;
      border-left: 3px solid #D4A851;
    }
    
    .titles-list {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
    }
    
    .title-badge {
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      padding: 8px 15px;
      border-radius: 20px;
      font-family: 'Cinzel', serif;
      font-size: 10pt;
    }
    
    .description-text {
      font-style: italic;
      padding: 10px;
      background: #f9f6f0;
      border-radius: 5px;
      border-left: 3px solid #D4A851;
    }
    
    .background-text {
      padding: 15px;
      background: #f9f6f0;
      border-radius: 5px;
      white-space: pre-wrap;
      line-height: 1.6;
    }
    
    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #D4A851;
      display: flex;
      justify-content: space-between;
      font-size: 9pt;
      color: #888;
    }
    
    .footer-note {
      text-align: center;
      margin-top: 20px;
      font-size: 8pt;
      color: #aaa;
    }
    
    .empty {
      color: #999;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <h1>BAROK GN</h1>
      <div class="subtitle">${labels.title}</div>
    </div>
    
    <div class="faction-name">${faction.nom}</div>
    
    <div class="section">
      <div class="section-title">${labels.destinyMarks}</div>
      <div class="marks-grid">
        <div class="mark-box">
          <div class="mark-label">${labels.total}</div>
          <div class="mark-value">${faction.marquesTotal}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.spent}</div>
          <div class="mark-value">${faction.marquesDepensees * 2}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.available}</div>
          <div class="mark-value">${faction.marquesDisponibles}</div>
        </div>
      </div>
    </div>
    
    <div class="section">
      <div class="section-title">${labels.landProperty}</div>
      ${faction.propriete 
        ? `<div class="info-value">${faction.propriete}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.buildingShip}</div>
      ${faction.batiment 
        ? `<div class="building-card">
            <div class="building-name">${translateBatiment(faction.batiment.nom)}</div>
            <div class="building-type">${batimentType}</div>
            <div class="building-advantages">${labels.advantages}: ${translateAvantage(faction.batiment.avantages)}</div>
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.titlesCareers}</div>
      ${faction.titres.length > 0 
        ? `<div class="titles-list">
            ${faction.titres.map(titre => 
              `<span class="title-badge">${translateTitre(titre)}</span>`
            ).join('')}
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.shortDescription}</div>
      ${faction.descriptionCourte 
        ? `<div class="description-text">${faction.descriptionCourte}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.background}</div>
      ${faction.background 
        ? `<div class="background-text">${faction.background}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="footer">
      <div>${labels.contactEmail}: ${faction.contactEmail}</div>
      <div>${labels.creationDate}: ${faction.dateCreation}</div>
    </div>
    
    <div class="footer-note">
      <p>${labels.autoGenerated} - Barok GN</p>
      <p>${labels.contactOrga}</p>
    </div>
  </div>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
};
