import { useLanguage } from "@/contexts/LanguageContext";
import { translateGameData } from "@/i18n/gameData";
import { Button } from "@/components/ui/button";
import { Printer, Download } from "lucide-react";
import { titresCarrieres } from "@/data/titres";

interface FactionSheetProps {
  faction: {
    nom: string;
    marquesTotal: number;
    marquesDepensees: number;
    marquesDisponibles: number;
    propriete: string;
    batiment: { type: string; nom: string; avantages: string } | null;
    titres: string[];
    descriptionCourte: string;
    background: string;
    contactEmail: string;
    dateCreation: string;
  };
}

// Helper function to get titre details
const getTitreDetails = (titreName: string) => {
  return titresCarrieres.find(t => t.nom === titreName);
};

export const FactionSheet = ({ faction }: FactionSheetProps) => {
  const { t, language } = useLanguage();

  const generateSheetHTML = () => {
    const labels = {
      title: language === 'en' ? 'FACTION SHEET' : 'FICHE DE FACTION',
      factionName: language === 'en' ? 'Faction Name' : 'Nom de la Faction',
      destinyMarks: language === 'en' ? 'Destiny Marks' : 'Marques de Destinée',
      total: language === 'en' ? 'Total' : 'Total',
      spent: language === 'en' ? 'Spent' : 'Dépensées',
      available: language === 'en' ? 'Available' : 'Disponibles',
      landProperty: language === 'en' ? 'Land Property' : 'Propriété Terrienne',
      buildingShip: language === 'en' ? 'Building/Ship' : 'Bâtiment/Navire',
      building: language === 'en' ? 'Building' : 'Bâtiment',
      ship: language === 'en' ? 'Ship' : 'Navire',
      advantages: language === 'en' ? 'Advantages' : 'Avantages',
      titlesCareers: language === 'en' ? 'Titles/Careers' : 'Titres/Carrières',
      prerequisites: language === 'en' ? 'Prerequisites' : 'Prérequis',
      incompatible: language === 'en' ? 'Incompatible with' : 'Incompatible avec',
      shortDescription: language === 'en' ? 'Short Description' : 'Description Courte',
      background: language === 'en' ? 'Complete Background' : 'Background Complet',
      contactEmail: language === 'en' ? 'Contact Email' : 'Email de Contact',
      creationDate: language === 'en' ? 'Creation Date' : 'Date de Création',
      none: language === 'en' ? 'None' : 'Aucun(e)',
      autoGenerated: language === 'en' ? 'Automatically generated sheet' : 'Fiche générée automatiquement',
      contactOrga: language === 'en' ? 'For any modification, contact the organization' : 'Pour toute modification, contactez l\'organisation',
      importantMessage: language === 'en' 
        ? 'IMPORTANT: Please print and save this faction sheet, then send it by email to: steampunk.barok@gmail.com'
        : 'IMPORTANT : Veuillez imprimer et sauvegarder cette fiche de faction, puis l\'envoyer par email à : steampunk.barok@gmail.com',
    };

    const batimentType = faction.batiment?.type === 'Bâtiment' 
      ? labels.building 
      : faction.batiment?.type === 'Navire' 
        ? labels.ship 
        : faction.batiment?.type || '';

    // Generate titles with details
    const titlesWithDetails = faction.titres.map(titre => {
      const titreData = getTitreDetails(titre);
      return {
        nom: titre,
        prerequis: titreData?.prerequis || '',
        incompatible: titreData?.incompatible || ''
      };
    });

    return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${faction.nom}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    @page {
      size: A4 portrait;
      margin: 12mm;
    }
    
    body {
      font-family: 'Crimson Text', Georgia, serif;
      background: #f5f0e6;
      color: #2c1810;
      font-size: 10pt;
      line-height: 1.3;
    }
    
    .sheet {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      padding: 15mm;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }
    
    @media print {
      body {
        background: #fff;
      }
      .sheet {
        box-shadow: none;
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
    }
    
    .header {
      text-align: center;
      border-bottom: 3px double #6B1836;
      padding-bottom: 12px;
      margin-bottom: 15px;
    }
    
    .header h1 {
      font-family: 'Cinzel', serif;
      font-size: 22pt;
      color: #6B1836;
      margin-bottom: 3px;
      letter-spacing: 3px;
    }
    
    .header .subtitle {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #D4A851;
      letter-spacing: 2px;
    }
    
    .faction-name {
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 18pt;
      color: #2c1810;
      margin: 15px 0;
      padding: 12px;
      background: linear-gradient(90deg, transparent, rgba(107,24,54,0.1), transparent);
      border-top: 1px solid #D4A851;
      border-bottom: 1px solid #D4A851;
    }
    
    .section {
      margin-bottom: 14px;
      page-break-inside: avoid;
    }
    
    .section-title {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #6B1836;
      border-bottom: 1px solid #D4A851;
      padding-bottom: 4px;
      margin-bottom: 8px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .marks-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      text-align: center;
    }
    
    .mark-box {
      padding: 12px;
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
    }
    
    .mark-label {
      font-size: 8pt;
      color: #666;
      margin-bottom: 4px;
      text-transform: uppercase;
    }
    
    .mark-value {
      font-family: 'Cinzel', serif;
      font-size: 18pt;
      color: #6B1836;
      font-weight: 600;
    }
    
    .info-row {
      display: flex;
      margin-bottom: 6px;
    }
    
    .info-label {
      font-weight: 600;
      color: #6B1836;
      min-width: 140px;
    }
    
    .info-value {
      flex: 1;
    }
    
    .building-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 12px;
    }
    
    .building-name {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #6B1836;
      margin-bottom: 4px;
    }
    
    .building-type {
      font-size: 8pt;
      color: #888;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    .building-advantages {
      font-style: italic;
      background: rgba(212,168,81,0.1);
      padding: 8px;
      border-radius: 3px;
      border-left: 3px solid #D4A851;
      font-size: 9pt;
    }
    
    .title-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 8px;
    }
    
    .title-name {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #6B1836;
      margin-bottom: 6px;
      display: inline-block;
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      padding: 4px 12px;
      border-radius: 15px;
    }
    
    .title-details {
      font-size: 9pt;
      margin-top: 6px;
    }
    
    .title-prereq {
      color: #2c6b18;
      margin-bottom: 3px;
    }
    
    .title-incomp {
      color: #b22222;
    }
    
    .description-text {
      font-style: italic;
      padding: 10px;
      background: #f9f6f0;
      border-radius: 5px;
      border-left: 3px solid #D4A851;
      font-size: 9pt;
    }
    
    .background-text {
      padding: 12px;
      background: #f9f6f0;
      border-radius: 5px;
      white-space: pre-wrap;
      line-height: 1.5;
      font-size: 9pt;
      max-height: none;
    }
    
    .footer {
      margin-top: 20px;
      padding-top: 12px;
      border-top: 1px solid #D4A851;
      display: flex;
      justify-content: space-between;
      font-size: 8pt;
      color: #888;
    }
    
    .footer-note {
      text-align: center;
      margin-top: 15px;
      font-size: 7pt;
      color: #aaa;
    }
    
    .important-message {
      margin-top: 20px;
      padding: 15px;
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      border-radius: 8px;
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      letter-spacing: 0.5px;
      box-shadow: 0 4px 15px rgba(107, 24, 54, 0.3);
    }
    
    .important-message strong {
      display: block;
      font-size: 13pt;
      margin-bottom: 8px;
      color: #D4A851;
    }
    
    .important-message a {
      color: #D4A851;
      text-decoration: underline;
    }
    
    .empty {
      color: #999;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <h1>BAROK GN</h1>
      <div class="subtitle">${labels.title}</div>
    </div>
    
    <div class="faction-name">${faction.nom}</div>
    
    <div class="section">
      <div class="section-title">${labels.destinyMarks}</div>
      <div class="marks-grid">
        <div class="mark-box">
          <div class="mark-label">${labels.total}</div>
          <div class="mark-value">${faction.marquesTotal}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.spent}</div>
          <div class="mark-value">${faction.marquesDepensees * 2}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.available}</div>
          <div class="mark-value">${faction.marquesDisponibles}</div>
        </div>
      </div>
    </div>
    
    <div class="section">
      <div class="section-title">${labels.landProperty}</div>
      ${faction.propriete 
        ? `<div class="info-value">${faction.propriete}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.buildingShip}</div>
      ${faction.batiment 
        ? `<div class="building-card">
            <div class="building-name">${translateGameData(faction.batiment.nom, 'batiment', language)}</div>
            <div class="building-type">${batimentType}</div>
            <div class="building-advantages">${labels.advantages}: ${translateGameData(faction.batiment.avantages, 'batimentAvantage', language)}</div>
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.titlesCareers}</div>
      ${titlesWithDetails.length > 0 
        ? titlesWithDetails.map(titre => `
            <div class="title-card">
              <span class="title-name">${translateGameData(titre.nom, 'titre', language)}</span>
              <div class="title-details">
                ${titre.prerequis ? `<div class="title-prereq"><strong>${labels.prerequisites}:</strong> ${translateGameData(titre.prerequis, 'titrePrerequisit', language)}</div>` : ''}
                ${titre.incompatible ? `<div class="title-incomp"><strong>${labels.incompatible}:</strong> ${titre.incompatible.split(', ').map(inc => translateGameData(inc.trim(), 'titre', language)).join(', ')}</div>` : ''}
              </div>
            </div>
          `).join('')
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.shortDescription}</div>
      ${faction.descriptionCourte 
        ? `<div class="description-text">${faction.descriptionCourte}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.background}</div>
      ${faction.background 
        ? `<div class="background-text">${faction.background}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="footer">
      <div>${labels.contactEmail}: ${faction.contactEmail}</div>
      <div>${labels.creationDate}: ${faction.dateCreation}</div>
    </div>
    
    <div class="footer-note">
      <p>${labels.autoGenerated} - Barok GN</p>
      <p>${labels.contactOrga}</p>
    </div>
    
    <div class="important-message">
      <strong>⚠️ ${language === 'en' ? 'IMPORTANT ACTION REQUIRED' : 'ACTION IMPORTANTE REQUISE'} ⚠️</strong>
      ${labels.importantMessage}
    </div>
  </div>
</body>
</html>
    `;
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(generateSheetHTML());
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(generateSheetHTML());
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  return (
    <div className="flex gap-2">
      <Button onClick={handlePrint} variant="outline" className="gap-2">
        <Printer className="h-4 w-4" />
        {language === 'en' ? 'Print' : 'Imprimer'}
      </Button>
      <Button onClick={handleDownloadPDF} className="gap-2">
        <Download className="h-4 w-4" />
        {language === 'en' ? 'Download PDF' : 'Télécharger PDF'}
      </Button>
    </div>
  );
};

export const openFactionSheet = (faction: {
  nom: string;
  marquesTotal: number;
  marquesDepensees: number;
  marquesDisponibles: number;
  propriete: string;
  batiment: { type: string; nom: string; avantages: string } | null;
  titres: string[];
  descriptionCourte: string;
  background: string;
  contactEmail: string;
  dateCreation: string;
}, language: 'fr' | 'en') => {
  const labels = {
    title: language === 'en' ? 'FACTION SHEET' : 'FICHE DE FACTION',
    factionName: language === 'en' ? 'Faction Name' : 'Nom de la Faction',
    destinyMarks: language === 'en' ? 'Destiny Marks' : 'Marques de Destinée',
    total: language === 'en' ? 'Total' : 'Total',
    spent: language === 'en' ? 'Spent' : 'Dépensées',
    available: language === 'en' ? 'Available' : 'Disponibles',
    landProperty: language === 'en' ? 'Land Property' : 'Propriété Terrienne',
    buildingShip: language === 'en' ? 'Building/Ship' : 'Bâtiment/Navire',
    building: language === 'en' ? 'Building' : 'Bâtiment',
    ship: language === 'en' ? 'Ship' : 'Navire',
    advantages: language === 'en' ? 'Advantages' : 'Avantages',
    titlesCareers: language === 'en' ? 'Titles/Careers' : 'Titres/Carrières',
    prerequisites: language === 'en' ? 'Prerequisites' : 'Prérequis',
    incompatible: language === 'en' ? 'Incompatible with' : 'Incompatible avec',
    shortDescription: language === 'en' ? 'Short Description' : 'Description Courte',
    background: language === 'en' ? 'Complete Background' : 'Background Complet',
    contactEmail: language === 'en' ? 'Contact Email' : 'Email de Contact',
    creationDate: language === 'en' ? 'Creation Date' : 'Date de Création',
    none: language === 'en' ? 'None' : 'Aucun(e)',
    autoGenerated: language === 'en' ? 'Automatically generated sheet' : 'Fiche générée automatiquement',
    contactOrga: language === 'en' ? 'For any modification, contact the organization' : 'Pour toute modification, contactez l\'organisation',
    importantMessage: language === 'en' 
      ? 'IMPORTANT: Please print and save this faction sheet, then send it by email to: steampunk.barok@gmail.com'
      : 'IMPORTANT : Veuillez imprimer et sauvegarder cette fiche de faction, puis l\'envoyer par email à : steampunk.barok@gmail.com',
  };

  const batimentType = faction.batiment?.type === 'Bâtiment' 
    ? labels.building 
    : faction.batiment?.type === 'Navire' 
      ? labels.ship 
      : faction.batiment?.type || '';

  // Helper function for translations
  const translateBatiment = (text: string) => {
    const batimentTranslations: Record<string, string> = {
      "QG de Faction": "Faction HQ",
      "Entrepôt": "Warehouse",
      "Laboratoire d'Alchimie": "Alchemy Laboratory",
      "Temple/Chapelle": "Temple/Chapel",
      "Académie": "Academy",
      "Tour d'Observation": "Observation Tower",
      "Salle de Réception": "Reception Hall",
      "Prison/Cachot": "Prison/Dungeon",
      "Forge/Atelier": "Forge/Workshop",
      "Barque fluviale": "River boat",
      "Galère": "Galley",
      "Navire de guerre": "Warship",
      "Navire marchand": "Merchant ship",
      "Zeppelin": "Zeppelin",
      "Navire volant": "Airship",
      "Cœur-fusible": "Fuse-Heart",
      "Résidence éthérée": "Ethereal Residence",
      "Jardin de méditation elfique": "Elven Meditation Garden",
      "Acierie Wellington-Barr": "Wellington-Barr Steelworks",
      "Eniversité": "Eniversity",
      "Ziggourat thanatonique": "Thanatonic Ziggurat",
      "Le navire rubis ravageur": "The Ruby Ravager Ship",
      "Caserne du CPAS": "CPAS Barracks",
      "Forge des Maîtres Nains": "Dwarven Masters Forge",
      "Laboratoire Alchimique": "Alchemical Laboratory",
      "Mine d'Abîme Maudit": "Cursed Abyss Mine",
      "Jardins Mystiques": "Mystical Gardens",
      "Distillerie des Mille Saveurs": "Thousand Flavors Distillery",
      "Arsenal Mécanique": "Mechanical Arsenal",
      "Nécropole Sacrée": "Sacred Necropolis",
      "Atelier du Tisserand Royal": "Royal Weaver's Workshop",
      "Observatoire Astral": "Astral Observatory",
      "Fonderie Industrielle Charbon": "Coal Industrial Foundry",
      "Conserverie de Luxe": "Luxury Cannery",
      "Chantier Naval": "Shipyard",
      "Marché aux Curiosités": "Curiosities Market",
      "Sanatorium Thermal": "Thermal Sanatorium",
      "Ferme Élevage Exotique": "Exotic Breeding Farm",
      "Cristallerie Magique": "Magical Glassworks",
      "Décharge Alchimique": "Alchemical Dump",
      "Bibliothèque d'étude": "Study Library",
      "Tonnellerie Légendaire": "Legendary Cooperage",
      "Bergerie": "Sheepfold",
      "Manufacture de Rouages": "Gear Manufactory",
      "Jardin Plantes Carnivores": "Carnivorous Plants Garden",
      "Fumoir Artisanal": "Artisan Smokehouse",
      "Atelier Soufflage Verre": "Glassblowing Workshop",
      "Campement mercenaire": "Mercenary Camp",
      "Oasis": "Oasis",
      "Atelier de Joaillerie": "Jewelry Workshop",
      "Rucher": "Apiary",
      "Fonderie du Crédit Nain": "Dwarven Credit Foundry",
      "Laboratoire expérimental": "Experimental Laboratory",
      "Camps Agence Anachronistes": "Anachronists Agency Camp",
      "La Vengeance du Kraken": "The Kraken's Vengeance",
      "Navire maritime": "Maritime Ship",
      "Navire-volant": "Flying Ship"
    };
    return language === 'en' ? (batimentTranslations[text] || text) : text;
  };

  const translateAvantage = (text: string) => {
    const avantageTranslations: Record<string, string> = {
      "Siège, réunions secrètes": "Headquarters, secret meetings",
      "Stockage de marchandises en masse": "Mass goods storage",
      "Préparation potions et expérimentations": "Potion preparation and experimentation",
      "Centre spirituel, rituels religieux": "Spiritual center, religious rituals",
      "Formation et enseignement": "Training and education",
      "Surveillance et repérage": "Surveillance and spotting",
      "Événements sociaux et politiques": "Social and political events",
      "Détention et interrogation": "Detention and interrogation",
      "Artisanat et réparations": "Crafting and repairs",
      "Transport fluvial léger": "Light river transport",
      "Transport fluvial et combat": "River transport and combat",
      "Combat naval, transport de troupes": "Naval combat, troop transport",
      "Commerce maritime, transport de marchandises": "Maritime trade, goods transport",
      "Transport aérien, reconnaissance": "Air transport, reconnaissance",
      "Combat aérien, transport de troupes": "Air combat, troop transport",
      "Permet d'avoir deux canons sur le navire": "Allows two cannons on the ship",
      "Contact avec Entités en cas de rituel": "Contact with Entities during rituals",
      "Récupère tous les points de vie pendant la méditation": "Recovers all life points during meditation",
      "Produit 10 Acier de plus/an": "Produces 10 more Steel/year",
      "Perte d'abîme de 2 points à soigner par an pour la faction": "Abyss loss of 2 points to heal per year for the faction",
      "200 morts-vivants mineurs / an": "200 minor undead / year",
      "1 bombe de sape / an": "1 sapping bomb / year",
      "20 balles en argent / an": "20 silver bullets / year"
    };
    return language === 'en' ? (avantageTranslations[text] || text) : text;
  };

  const translateTitre = (text: string) => {
    const titreTranslations: Record<string, string> = {
      "Adepte": "Follower",
      "Agent d'une ONG": "NGO Agent",
      "Ancien Esclave": "Former slave",
      "Archiviste des Secrets": "Archivist",
      "Artiste d'une Compagnie": "Artist",
      "Bourgeois": "Bourgeois",
      "Capitaine de Navire": "Ship captain",
      "Capitaine Navire-Volant": "Airship captain",
      "Chef de Bande Organisée": "Bandit leader",
      "Contrebandier": "Smuggler",
      "Corsaire elfique": "Elven corsair",
      "Épervier": "Sparrowhawk",
      "Garde du Corps": "Bodyguard",
      "Gestionnaire de Dépôt": "Warehouse Manager",
      "Greffier": "Clerk",
      "Mercenaire Peau-olive": "Olive-skinned mercenary",
      "Noblesse de Sang": "Blood Nobility",
      "Ordre Chevaliers Suie (LAM)": "AML",
      "Pirate": "Pirate",
      "Planaire": "Planar",
      "Porteur de Rune": "Rune Bearer",
      "Prévôt du Crépuscule": "Provost of the Twilight",
      "Sectaire ésotérico-magique": "Esoteric-magical sect",
      "Sergent de l'ombre": "Shadow Sergeant",
      "Démuni": "Outcast",
      "Enquêteur": "Investigator",
      "Enquêteur public": "Public investigator",
      "Milicien": "Militiaman",
      "Magistrat": "Magistrate",
      "LAM": "AML",
      "Autres fonctionnaires": "Other civil servants",
      "Tous fonctionnaires": "All civil servants",
      "Pirates": "Pirates",
      "Planaires": "Planars",
      "Sectaire": "Sectarian"
    };
    return language === 'en' ? (titreTranslations[text] || text) : text;
  };

  const translatePrereq = (text: string) => {
    const prereqTranslations: Record<string, string> = {
      "Culte en jeu": "Cult in game",
      "Background + Entrave + Évasion": "Background + Handcuff + Escape",
      "Alphabétisation commune": "Common literacy",
      "Talent artistique RP": "RP artistic talent",
      "Navire TO + Notaire": "TO Ship + Notary",
      "Navire-volant TO + Notaire": "TO Flying Ship + Notary",
      "Filouterie": "Shady skill",
      "Compétence Contrebandier": "Smuggler skill",
      "Background éthique": "Ethical background",
      "Background + Capitaine Navire/Navire-Volant": "Background + Ship/Airship Captain",
      "Menuisier": "Carpenter",
      "Alphab. avancée + Solde": "Advanced literacy + Salary",
      "Orcs/Gobelins/Trolls + Background": "Orcs/Goblins/Trolls + Background",
      "Background liens noblesse": "Nobility ties background",
      "Haine magie + Compétence technologie/mécanique/forgeron": "Magic hatred + Technology/mechanics/blacksmith skill",
      "Background + Code Piraterie": "Background + Piracy Code",
      "Background extraplanaire": "Extraplanar background",
      "Nains/Gnomes/Sautaises + Forgeron": "Dwarves/Gnomes/Sautais + Blacksmith",
      "Mystique": "Mystic",
      "Filouterie + deux compétences Martiales": "Shady + two Martial skills"
    };
    return language === 'en' ? (prereqTranslations[text] || text) : text;
  };

  // Get titre details
  const getTitreDetailsLocal = (titreName: string) => {
    return titresCarrieres.find(t => t.nom === titreName);
  };

  // Generate titles with details
  const titlesWithDetails = faction.titres.map(titre => {
    const titreData = getTitreDetailsLocal(titre);
    return {
      nom: titre,
      prerequis: titreData?.prerequis || '',
      incompatible: titreData?.incompatible || ''
    };
  });

  const html = `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${faction.nom}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    @page {
      size: A4 portrait;
      margin: 12mm;
    }
    
    body {
      font-family: 'Crimson Text', Georgia, serif;
      background: #f5f0e6;
      color: #2c1810;
      font-size: 10pt;
      line-height: 1.3;
    }
    
    .sheet {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      padding: 15mm;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }
    
    @media print {
      body {
        background: #fff;
      }
      .sheet {
        box-shadow: none;
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
    }
    
    .header {
      text-align: center;
      border-bottom: 3px double #6B1836;
      padding-bottom: 12px;
      margin-bottom: 15px;
    }
    
    .header h1 {
      font-family: 'Cinzel', serif;
      font-size: 22pt;
      color: #6B1836;
      margin-bottom: 3px;
      letter-spacing: 3px;
    }
    
    .header .subtitle {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #D4A851;
      letter-spacing: 2px;
    }
    
    .faction-name {
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 18pt;
      color: #2c1810;
      margin: 15px 0;
      padding: 12px;
      background: linear-gradient(90deg, transparent, rgba(107,24,54,0.1), transparent);
      border-top: 1px solid #D4A851;
      border-bottom: 1px solid #D4A851;
    }
    
    .section {
      margin-bottom: 14px;
      page-break-inside: avoid;
    }
    
    .section-title {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #6B1836;
      border-bottom: 1px solid #D4A851;
      padding-bottom: 4px;
      margin-bottom: 8px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .marks-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      text-align: center;
    }
    
    .mark-box {
      padding: 12px;
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
    }
    
    .mark-label {
      font-size: 8pt;
      color: #666;
      margin-bottom: 4px;
      text-transform: uppercase;
    }
    
    .mark-value {
      font-family: 'Cinzel', serif;
      font-size: 18pt;
      color: #6B1836;
      font-weight: 600;
    }
    
    .info-row {
      display: flex;
      margin-bottom: 6px;
    }
    
    .info-label {
      font-weight: 600;
      color: #6B1836;
      min-width: 140px;
    }
    
    .info-value {
      flex: 1;
    }
    
    .building-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 12px;
    }
    
    .building-name {
      font-family: 'Cinzel', serif;
      font-size: 12pt;
      color: #6B1836;
      margin-bottom: 4px;
    }
    
    .building-type {
      font-size: 8pt;
      color: #888;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    .building-advantages {
      font-style: italic;
      background: rgba(212,168,81,0.1);
      padding: 8px;
      border-radius: 3px;
      border-left: 3px solid #D4A851;
      font-size: 9pt;
    }
    
    .title-card {
      background: #f9f6f0;
      border: 1px solid #D4A851;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 8px;
    }
    
    .title-name {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      color: #6B1836;
      margin-bottom: 6px;
      display: inline-block;
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      padding: 4px 12px;
      border-radius: 15px;
    }
    
    .title-details {
      font-size: 9pt;
      margin-top: 6px;
    }
    
    .title-prereq {
      color: #2c6b18;
      margin-bottom: 3px;
    }
    
    .title-incomp {
      color: #b22222;
    }
    
    .description-text {
      font-style: italic;
      padding: 10px;
      background: #f9f6f0;
      border-radius: 5px;
      border-left: 3px solid #D4A851;
      font-size: 9pt;
    }
    
    .background-text {
      padding: 12px;
      background: #f9f6f0;
      border-radius: 5px;
      white-space: pre-wrap;
      line-height: 1.5;
      font-size: 9pt;
      max-height: none;
    }
    
    .footer {
      margin-top: 20px;
      padding-top: 12px;
      border-top: 1px solid #D4A851;
      display: flex;
      justify-content: space-between;
      font-size: 8pt;
      color: #888;
    }
    
    .footer-note {
      text-align: center;
      margin-top: 15px;
      font-size: 7pt;
      color: #aaa;
    }
    
    .important-message {
      margin-top: 20px;
      padding: 15px;
      background: linear-gradient(135deg, #6B1836, #8B2346);
      color: #fff;
      border-radius: 8px;
      text-align: center;
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      letter-spacing: 0.5px;
      box-shadow: 0 4px 15px rgba(107, 24, 54, 0.3);
    }
    
    .important-message strong {
      display: block;
      font-size: 13pt;
      margin-bottom: 8px;
      color: #D4A851;
    }
    
    .important-message a {
      color: #D4A851;
      text-decoration: underline;
    }
    
    .empty {
      color: #999;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <h1>BAROK GN</h1>
      <div class="subtitle">${labels.title}</div>
    </div>
    
    <div class="faction-name">${faction.nom}</div>
    
    <div class="section">
      <div class="section-title">${labels.destinyMarks}</div>
      <div class="marks-grid">
        <div class="mark-box">
          <div class="mark-label">${labels.total}</div>
          <div class="mark-value">${faction.marquesTotal}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.spent}</div>
          <div class="mark-value">${faction.marquesDepensees * 2}</div>
        </div>
        <div class="mark-box">
          <div class="mark-label">${labels.available}</div>
          <div class="mark-value">${faction.marquesDisponibles}</div>
        </div>
      </div>
    </div>
    
    <div class="section">
      <div class="section-title">${labels.landProperty}</div>
      ${faction.propriete 
        ? `<div class="info-value">${faction.propriete}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.buildingShip}</div>
      ${faction.batiment 
        ? `<div class="building-card">
            <div class="building-name">${translateBatiment(faction.batiment.nom)}</div>
            <div class="building-type">${batimentType}</div>
            <div class="building-advantages">${labels.advantages}: ${translateAvantage(faction.batiment.avantages)}</div>
          </div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.titlesCareers}</div>
      ${titlesWithDetails.length > 0 
        ? titlesWithDetails.map(titre => `
            <div class="title-card">
              <span class="title-name">${translateTitre(titre.nom)}</span>
              <div class="title-details">
                ${titre.prerequis ? `<div class="title-prereq"><strong>${labels.prerequisites}:</strong> ${translatePrereq(titre.prerequis)}</div>` : ''}
                ${titre.incompatible ? `<div class="title-incomp"><strong>${labels.incompatible}:</strong> ${titre.incompatible.split(', ').map(inc => translateTitre(inc.trim())).join(', ')}</div>` : ''}
              </div>
            </div>
          `).join('')
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.shortDescription}</div>
      ${faction.descriptionCourte 
        ? `<div class="description-text">${faction.descriptionCourte}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="section">
      <div class="section-title">${labels.background}</div>
      ${faction.background 
        ? `<div class="background-text">${faction.background}</div>` 
        : `<div class="empty">${labels.none}</div>`}
    </div>
    
    <div class="footer">
      <div>${labels.contactEmail}: ${faction.contactEmail}</div>
      <div>${labels.creationDate}: ${faction.dateCreation}</div>
    </div>
    
    <div class="footer-note">
      <p>${labels.autoGenerated} - Barok GN</p>
      <p>${labels.contactOrga}</p>
    </div>
    
    <div class="important-message">
      <strong>⚠️ ${language === 'en' ? 'IMPORTANT ACTION REQUIRED' : 'ACTION IMPORTANTE REQUISE'} ⚠️</strong>
      ${labels.importantMessage}
    </div>
  </div>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
};
